package telas;


import dados.AppDao;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.sql.ResultSet;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author vinicius.tlira
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    public Menu(String cargo) {
        initComponents();
        if (cargo.equalsIgnoreCase("Gerente")) {

        } else if (cargo.equalsIgnoreCase("Estágiario")) {
            mnuDepartamentos.setVisible(false);
            mnuUsuarios.setVisible(false);

        } else if (cargo.equalsIgnoreCase("Analista")) {
            mnuDepartamentos.setVisible(false);
            itmCadastrarFuncionarios.setEnabled(false);
            itmAlterarFuncionarios.setEnabled(false);
            itmExcluirFuncionarios.setEnabled(false);

        } else if (cargo.equalsIgnoreCase("Vendedor")) {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuDepartamentos = new javax.swing.JMenu();
        itmCadastrarDepartamento = new javax.swing.JMenuItem();
        itmCadastrarFuncionarios = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        itmAlterarFuncionarios = new javax.swing.JMenuItem();
        itmConsultarFuncionarios = new javax.swing.JMenuItem();
        itmExcluirFuncionarios = new javax.swing.JMenuItem();
        itmListarFuncionarios = new javax.swing.JMenuItem();
        mnuUsuarios = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        itmExcluirUsuario = new javax.swing.JMenuItem();
        itmAlterarUsuario = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        itmBuscarUsuarios = new javax.swing.JMenuItem();
        itmListarUsuarios = new javax.swing.JMenuItem();
        mnuAjuda = new javax.swing.JMenu();
        mnuDocumentacao = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\vinicius.tlira\\papel-de-parede-hamburguer-lanche-cozinha-kit-02-rolos-a490-adesivo-acougue.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 590, 350);

        mnuDepartamentos.setText("Departamentos");

        itmCadastrarDepartamento.setText("Cadastrar ");
        itmCadastrarDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmCadastrarDepartamentoActionPerformed(evt);
            }
        });
        mnuDepartamentos.add(itmCadastrarDepartamento);

        jMenuBar1.add(mnuDepartamentos);

        itmCadastrarFuncionarios.setText("Funcionários");

        jMenuItem2.setText("Cadastrar ");
        itmCadastrarFuncionarios.add(jMenuItem2);

        itmAlterarFuncionarios.setText("Alterar");
        itmCadastrarFuncionarios.add(itmAlterarFuncionarios);

        itmConsultarFuncionarios.setText("Consultar");
        itmConsultarFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmConsultarFuncionariosActionPerformed(evt);
            }
        });
        itmCadastrarFuncionarios.add(itmConsultarFuncionarios);

        itmExcluirFuncionarios.setText("Excluir");
        itmCadastrarFuncionarios.add(itmExcluirFuncionarios);

        itmListarFuncionarios.setText("Listar");
        itmCadastrarFuncionarios.add(itmListarFuncionarios);

        jMenuBar1.add(itmCadastrarFuncionarios);

        mnuUsuarios.setText("Usuários ");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setText("Cadastrar ");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mnuUsuarios.add(jMenuItem1);

        itmExcluirUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itmExcluirUsuario.setText("Excluir");
        itmExcluirUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmExcluirUsuarioActionPerformed(evt);
            }
        });
        mnuUsuarios.add(itmExcluirUsuario);

        itmAlterarUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itmAlterarUsuario.setText("Alterar");
        itmAlterarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmAlterarUsuarioActionPerformed(evt);
            }
        });
        mnuUsuarios.add(itmAlterarUsuario);
        mnuUsuarios.add(jSeparator1);

        itmBuscarUsuarios.setText("Buscar");
        itmBuscarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmBuscarUsuariosActionPerformed(evt);
            }
        });
        mnuUsuarios.add(itmBuscarUsuarios);

        itmListarUsuarios.setText("Listar");
        itmListarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmListarUsuariosActionPerformed(evt);
            }
        });
        mnuUsuarios.add(itmListarUsuarios);

        jMenuBar1.add(mnuUsuarios);

        mnuAjuda.setText("Ajuda");

        mnuDocumentacao.setText("Documentação");

        jMenuItem6.setText("Manual do Usuario");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        mnuDocumentacao.add(jMenuItem6);

        jMenuItem7.setText("Sobre");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        mnuDocumentacao.add(jMenuItem7);

        mnuAjuda.add(mnuDocumentacao);

        jMenuBar1.add(mnuAjuda);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(605, 359));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itmExcluirUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmExcluirUsuarioActionPerformed
        String u;
        u = JOptionPane.showInputDialog("Usuario a excluir");
        //Conectar com o Banco de Dados 
        try {
           int retorno = new AppDao().excluirUsuario(u);
            if (retorno == 1) {
                JOptionPane.showMessageDialog(null, "Usuario excluido com sucesso ");
            } else {
                JOptionPane.showMessageDialog(null, "Usuario não existente ");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro:" + ex.getMessage());

        }
    }//GEN-LAST:event_itmExcluirUsuarioActionPerformed

    private void itmListarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmListarUsuariosActionPerformed
        new ListarUsuarios().setVisible(true);
        
    }//GEN-LAST:event_itmListarUsuariosActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new CadastrarUsuarios().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void itmCadastrarDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmCadastrarDepartamentoActionPerformed
        new CadastrarDepartamento().setVisible(true);
    }//GEN-LAST:event_itmCadastrarDepartamentoActionPerformed

    private void itmConsultarFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmConsultarFuncionariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itmConsultarFuncionariosActionPerformed

    private void itmAlterarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAlterarUsuarioActionPerformed
       
    }//GEN-LAST:event_itmAlterarUsuarioActionPerformed

    private void itmBuscarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmBuscarUsuariosActionPerformed
 // 1 - Perguntar o usuario a alterar
        String u;
        u = JOptionPane.showInputDialog("Usuario a alterar: ");
        try {
           ResultSet usuario = new AppDao().buscarUsuarios(u);
            //4 - Verifica se encontrou o usuário informado 
            if (usuario.next()) { // se encontrou
                //carregar os dados em outra janela(formulário)
            new AlterarUsuarios(usuario).setVisible(true);
            } else { // se não encontrou 
                JOptionPane.showMessageDialog(null, "Usuário não encontrado");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro" + ex.getMessage());
        }
    }//GEN-LAST:event_itmBuscarUsuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itmAlterarFuncionarios;
    private javax.swing.JMenuItem itmAlterarUsuario;
    private javax.swing.JMenuItem itmBuscarUsuarios;
    private javax.swing.JMenuItem itmCadastrarDepartamento;
    private javax.swing.JMenu itmCadastrarFuncionarios;
    private javax.swing.JMenuItem itmConsultarFuncionarios;
    private javax.swing.JMenuItem itmExcluirFuncionarios;
    private javax.swing.JMenuItem itmExcluirUsuario;
    private javax.swing.JMenuItem itmListarFuncionarios;
    private javax.swing.JMenuItem itmListarUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu mnuAjuda;
    private javax.swing.JMenu mnuDepartamentos;
    private javax.swing.JMenu mnuDocumentacao;
    private javax.swing.JMenu mnuUsuarios;
    // End of variables declaration//GEN-END:variables
}
